version: '3'

services:
  mongo-4:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: vapor_username
      MONGO_INITDB_ROOT_PASSWORD: vapor_password
    ports:
      - 27017:27017
