name: test
on:
- pull_request
jobs:
  xenial:
    container: 
      image: vapor/swift:5.2-xenial
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
      env:
        POSTGRES_HOSTNAME: mongo
  bionic:
    container: 
      image: vapor/swift:5.2-bionic
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
      env:
        POSTGRES_HOSTNAME: mongo
